### ISSUE TITLE
Suivi du plugin

### ISSUE THREAD

**Issue by Amigagame** [Sigri44/sigri_linky#10]
Bonjour

Utilisateur de votre plugin je voulais savoir si il était maintenu et si vous souhaitiez continuer le développement ?

Merci !

**Comment by Sigri44** [comment]
> Bonjour
> 
> Utilisateur de votre plugin je voulais savoir si il était maintenu et si vous souhaitiez continuer le développement ?
> 
> Merci !

Bonjour,

Il est actif et fonctionnel. Sur la V4 normalement tout passe aussi, sauf le widget mais je prévois un tutoriel rapide pour y accéder.

Merci.

**Comment by Amigagame** [comment]
Ok merci, enfait je parlais du bug avec J-1, mes courbes se chevauchent aussi certains jours (en ce moment je n'ai pas d'info pour le 11/11 mais sur le 10 j'ai les deux courbes à priori (du 10 et du 11)
