### ISSUE TITLE
Plugin non fonctionnel en V4

### ISSUE THREAD

**Issue by romainbecheau** [Sigri44/sigri_linky#18]
Bonjour Sigri,

tout d'abord je te remercie pour ce plugin, et je m'excuse si mon bug est hors sujet (car en Jeedom v4) , donc hésite pas a le cloturer.

J'ai installer via ton repot github le plugin

j'ai ajouté un 'équipement' nommé 'linky'

renseigné mes id enedis (que j'ai revérifié)

dès que j'ai cliquer sur sur 'sauvegarder' j'ai une erreur javascript dans jeedom

Fichier | Ligne | Message
-- | -- | --
https://www.jeedom.frixo.fr/3rdparty/jquery.contextMenu/jquery.contextMenu.min.js?md5=846adf0510b536c22314092ac9513842 | 1 | Uncaught TypeError: Cannot read property 'events' of undefined

Et si je test les 4 fonctions, toutes me retourne '' (vide)

je ne trouve aucun log a mon grand désespoir

une idée ? est ce que c'est juste du a la V4 ?

merci pour ton aide

Romain

**Comment by romainbecheau** [comment]
Hourra, j'ai attendu un peu et j'ai les valeurs qui remonte ! Mais j'ai encore l'erreur js !

**Comment by Sigri44** [comment]
Étonnant, ça a déjà été testé en v4 par plusieurs et de mémoire tout est fixé. D'ici quelques semaines je trouverais du temps pour tester tout ça !
Je réouvre pour garder l'erreur JS sous la main.

Merci !

**Comment by navycrow** [comment]
je suis en v4. et tout fonctionne parfaitement chez moi
