### ISSUE TITLE
Utilisation de la nouvelle API

### ISSUE THREAD

**Issue by wixaw** [Sigri44/sigri_linky#2]
Bonjour @Sigri44 

Est ce que le plugin fonctionne actuellement avec l'API ? 
Quand je veux ajouter un nouveau compteur, il est demandé une commande de télémétrie, mais je ne sais pas quoi ajouter. 
Est ce qu'il faut utiliser ce qu'il y a dans la doc https://datahub-enedis.fr/data-connect/documentation/metering-data/ ?

Merci
William

**Comment by Sigri44** [comment]
Hello @wixaw !

Actuellement non, l'API demande une inscription ainsi qu'une demande de création d'application afin qu'ils valident et envoient un token (prend du temps chez eux, et fastidieux pour "Madame Michu").
De plus une fois le saint graal obtenu, il faut demander l'autorisation à l'accès au data (en attente depuis + 2 mois pour moi, ainsi qu'à la courbe de charge).

Sinon oui la doc sera utile après, affaire à suivre !

**Comment by wixaw** [comment]
J'ai fais ma demande de token également, j'espère qu'ils vont débloquer la situation. C'est quand même étonnant ça semble être une API pour offrir le service à X clients et pas une API personnelle lié à son compte uniquement.
Je te tiens au jus de mon coté quand j'aurais reçu les infos

**Comment by Sigri44** [comment]
Ca marche merci, j'aurais du temps de dev dessus courant Avril je pense.

Il faut que je m'y remette pour voir le fonctionnement exact :)

**Comment by wixaw** [comment]
Salut, 
J'ai reçu ma clé, si tu as besoin de tests ou un coup de main pour l'API, je peux filer un coup de main.
A+

**Comment by Sigri44** [comment]
Ok merci ! J'essaye de voir si je peux avancer dans la semaine :)

**Comment by Jaxom99** [comment]
Bonjour,
Tombé sur ce projet dans mes recherches, je me permets d'intervenir car on a creusé cette nouvelle API avec des collègues : c'est bien destiné aux pros, il faut un front-end joli avec parcours client "charte graphique Enedis". On a un début de doc ici : https://wiki.consometers.org/doku.php?id=projets:dataconnect
La logique est très différente de l'espace client enedis ! Ceci étant on reste aux aguets, on a des structures pro/asso qui pourraient se positionner pour faire l'intermédiaire...
Au plaisir,
Jaxom

**Comment by Sigri44** [comment]
> Bonjour,
> Tombé sur ce projet dans mes recherches, je me permets d'intervenir car on a creusé cette nouvelle API avec des collègues : c'est bien destiné aux pros, il faut un front-end joli avec parcours client "charte graphique Enedis". On a un début de doc ici : https://wiki.consometers.org/doku.php?id=projets:dataconnect
> La logique est très différente de l'espace client enedis ! Ceci étant on reste aux aguets, on a des structures pro/asso qui pourraient se positionner pour faire l'intermédiaire...
> Au plaisir,
> Jaxom

Hello !

Effectivement c'est pas évidement aux premiers abords. Mais nous avons un membre d'Enedis sur notre forum Domotique, et il nous a certifié que les particuliers avait 100% accès aux datas au même titre que l'espace client. Mais avouons le, c'est l'usine à gaz afin d'obtenir l'accès API.
Je suis en train de faire le dev au webservice, mais je ne sais pas comment les gens vont pouvoir obtenir facilement leurs credentials.
