### ISSUE TITLE
Nouvelle interface

### ISSUE THREAD

**Issue by navycrow** [Sigri44/sigri_linky#20]
Je ne comprend pas ce commentaire : "Comme prévu depuis plusieurs mois, Enedis a entièrement mis à jour son interface en intégrant un Captcha. C'est donc désormais impossible de crawler le site, je suis donc toujours en attente d'un système pour pouvoir interroger leur API."

De mon côté, malgré la nouvelle interface, j'ai bien les données qui remontent.

**Comment by Sigri44** [comment]
> 
> 
> Je ne comprend pas ce commentaire : "Comme prévu depuis plusieurs mois, Enedis a entièrement mis à jour son interface en intégrant un Captcha. C'est donc désormais impossible de crawler le site, je suis donc toujours en attente d'un système pour pouvoir interroger leur API."
> 
> De mon côté, malgré la nouvelle interface, j'ai bien les données qui remontent.

Oui car tu as une "session"/cookie encore ouverte, du coup dès son expiration (de 7 à 30j suivant le module et la config) alors tu ne pourras plus te reconnecter. J'ai fait pas mal de tests et sur une fresh install c'est cuit ! Les jours sont comptés.

**Comment by navycrow** [comment]
ah. ca craint !! Je trouvais ça vachement bien.
Je pensais qu'ils avait une API en libre service (data.enedis.fr)...
J'espère que tu va trouver une solution.

**Comment by Sigri44** [comment]
> 
> 
> ah. ca craint !! Je trouvais ça vachement bien.
> Je pensais qu'ils avait une API en libre service (data.enedis.fr)...
> J'espère que tu va trouver une solution.

Il y'en a, mais elle n'est pas "ouverte", ce qui signifie que chaque utilisateur doit y déclarer son application afin d'y voir accorder l'accès. Hyper contre-productif, à moins que Jeedom fasse une demande par exemple, mais trop de galère..

**Comment by submarcos** [comment]
Il y a d'autres plugins jeedom qui fonctionnent de la sorte. Netatmo par exemple, on doit créer une appli sur l'API netatmo et renseigner ses identifiants d'acces ET d'appli dans le plugin jeedom. Ca serait dommage de plus pouvoir utiliser ce plugin

**Comment by bart11064** [comment]
Je suis d'accord avec @submarcos : d'autres plugins nécessite la création d'une application comme les biens connus plugin google (tts, ghome, etc...)
La mise en place est plus longue, mais rien d'impossible, et on le fait une fois pour toute.

**Comment by Sigri44** [comment]
Hello,

Pour Netamo je vais creuser ! Là la différence est qu'il faut s’enregistrer comme Société auprès d'Enedis, malheureusement tout le monde n'en dispose pas... Mais oui je prends note de vos demande, et vais creuser un peu plus l'API. Je fais au mieux ! Merci

**Comment by bart11064** [comment]
Je viens de faire une demande d'accès auprès d'Enedis dans le bac à sable. Dans la section où j'ai demandé (https://datahub-enedis.fr/data-connect/gerer-mon-service/creer-une-application/) pas d'enregistrement de personne morale. Peut-être est-ce suffisant ?

**Comment by Sigri44** [comment]
> 
> 
> Je viens de faire une demande d'accès auprès d'Enedis dans le bac à sable. Dans la section où j'ai demandé (https://datahub-enedis.fr/data-connect/gerer-mon-service/creer-une-application/) pas d'enregistrement de personne morale. Peut-être est-ce suffisant ?
> Merci en tout cas pour ton travail ! 1st_place_medal

Hello, oui ça semble être la nouvelle interface, pas besoin de SIRET, une clé API est proposée ? Si oui ça serait le top !

**Comment by bart11064** [comment]
J'ai reçu un sms avec ce qui ressemble à une clé API effectivement.
Après je ne suis pas persuadé : ca donne accès au bac à sable qui contient des données factices apparemment. Il faut ensuite passer en production, et là on va peut-être retomber dans le cas de figure précédent (SIRET, ...)

**Comment by navycrow** [comment]
Bon et bien voilà, depuis 2 jours le plugin me retourne une erreur et plus possible de récupérer les index (ça continuais à fonctionner depuis des mois). Dommage.
Y'a t-il moyen de réactiver quelque chose ou c'est mort??

**Comment by Sigri44** [comment]
> 
> 
> Bon et bien voilà, depuis 2 jours le plugin me retourne une erreur et plus possible de récupérer les index (ça continuais à fonctionner depuis des mois). Dommage.
> Y'a t-il moyen de réactiver quelque chose ou c'est mort??

J'ai le même soucis aussi et j'ai eu une dizaine de remontées dans ce genre. Je pense que le plugin va mourir et quand j'arriverais à sortir un DataConnect 100% fonctionnel ça ressortira.

**Comment by navycrow** [comment]
Je me demandais, puisque une fois acquis, le token semble valide plusieurs mois (je dirais au moins 3 ou 4 mois). N'est-il pas possible soit :
- de rentrer le token directement dans un champs au lieu des identifiants (après l'avoir récupérer via une connection classique sur un navigateur)
- d'ouvrir la page enedis depuis jeedom pour se reconnecter et obtenir un nouveau token

C'est pas super classe comme procédé, mais bon à défaut de mieux, ça dépannerai le temps de trouver une alternative.

**Comment by FloLaco** [comment]
Il suffirait d'intégrer l'API de anti-captcha.com pour pouvoir continuer a requeter le site en php/python

**Comment by FloLaco** [comment]
@Sigri44 Il suffirait d'intégrer l'API d'anti-captcha.com pour pouvoir continuer a requeter le site en php/python

**Comment by Sigri44** [comment]
> anti-captcha.com

Il n'y a pas qu'eux, ils suffit juste que vous payez vos captcha, un peu kafkaïen pour de la domotique ! (sinon il y a 2captcha qui fait ça 100 fois mieux).

Sinon vrai solution, utiliser le plugin Enedis officiel Jeedom désormais.

**Comment by FloLaco** [comment]
> > anti-captcha.com
> 
> Il n'y a pas qu'eux, ils suffit juste que vous payez vos captcha, un peu kafkaïen pour de la domotique ! (sinon il y a 2captcha qui fait ça 100 fois mieux).
> 
> Sinon vrai solution, utiliser le plugin Enedis officiel Jeedom désormais.

Un peu d'accord qu'utiliser ce service pour de la domo c'est dommage. Mais quand y a pas le choix ...

le plugin officiel ne fonctionne que si on a accès à l'espace pro, ce qui est rarement le cas, ou de manière assez aléatoire.

**Comment by navycrow** [comment]
Pour info, Jeedom a sorti il y a quelques semaines un plugin officiel Enedis.
Depuis ces derniers jours, il est désormais 100% fonctionnel pour les particuliers.

**Comment by schmurtzm** [comment]
> 
> 
> Pour info, Jeedom a sorti il y a quelques semaines un plugin officiel Enedis.
> Depuis ces derniers jours, il est désormais 100% fonctionnel pour les particuliers.

Es tu certain que ce soit "officiel" ?
J'ai plutot l'impression que c'est basé sur une api réalisée par un particulier :
https://forum.hacf.fr/t/enedis-gateway/868

Par contre si c'est le cas Jeedom n'a pas eu la délicatesse d'annoncer à ses utilisateur que leur plugin fait transiter les données d'Enedis via un serveur tenu par eux même ou par un particulier.... C'est limite je trouve...

**Comment by navycrow** [comment]
Je ne parle pas d'enedis gateway mais de [Linky enedis](https://doc.jeedom.com/fr_FR/plugins/energy/enedis/).
C'est bien un plugin officiel. C'est indiqué comme tel sur le market jeedom.
Et lors de l'installation, il faut passer par le site enedis qui te demande ton accord pour que jeedom récupère les données, donc je vois pas ou est le souci.
C'est fait dans les règles.
Personnellement, ça ne me pose aucun problème.

**Comment by Sigri44** [comment]
Le plugin officiel est simplement une évolution du mien, il se connecte directement à Enedis !

Pour ce qui est de la Gateway (le tuto est pour homeassistant), il y'a effectivement une passerelle qui passe par un tiers particulier. Pour ça que je n'ai jamais mis en place ce système car ne respecte pas RGPD de mon point de vue.

**Comment by schmurtzm** [comment]
> 
> 
> Le plugin officiel est simplement une évolution du mien, il se connecte directement à Enedis !
> 
> Pour ce qui est de la Gateway (le tuto est pour homeassistant), il y'a effectivement une passerelle qui passe par un tiers particulier. Pour ça que je n'ai jamais mis en place ce système car ne respecte pas RGPD de mon point de vue.

Merci pour cette info. Le plugin officiel n'étant pas open source, c'était difficile de dire si c'est une évolution du tiens ou autre chose.
Ce qui m'intrigue c'est qu'il n'existe pas à ma connaissance d'API ouverte aux particuliers chez Enedis... L'API "data connect" est réservée aux pros et nécessite un numéro de Siret.  
https://github.com/consometers/data-connect

Du coup je suis intrigué par ce plugin jeedom... Quelle API peuvent-ils bien utiliser ? N'ont-il pas plutot créé leur propre passerelle ?

**Comment by FloLaco** [comment]
Jeedom est une societé, ils ont accès à l'API. 
Il y a eu une annonce de Jeedom pour dire qu'ils travaillaient à fournir le plugin pour tous grace a la signature de contrat entre enedis et Jeedom.

Du coup, le plugin ne passe pas par une API tiers mais directement par une API Jeedom. 

-- 
Florian Lacommare

**Comment by schmurtzm** [comment]
> Jeedom est une societé, ils ont accès à l'API. Il y a eu une annonce de Jeedom pour dire qu'ils travaillaient à fournir le plugin pour tous grace a la signature de contrat entre enedis et Jeedom. Du coup, le plugin ne passe pas par une API tiers mais directement par une API Jeedom.
>
Bon à savoir, merci pour l'info. Il est regrettable qu'Enedis ne mette pas à disposition elle même une API comme c'était le cas auparavant...

La responsabilité de Jeedom est grande car (sans sombrer dans la paranoïa), les informations liées à la consommation électrique en disent beaucoup sur une habitation (je pense notamment aux habitudes de vie mais surtout aux heures de présence). Du coup expliquer à l'utilisateur que les données transitent via un tiers me parais fair play. Mais bon ce n'est pas mon combat, juste une opinion  ;)

Merci en tous cas pour vos éclaircissements !

**Comment by Sigri44** [comment]
Autant pour moi, je n'avais pas vu la dernière MàJ ! Effectivement désormais Jeedom utilise l'API datahub en direct et est sa propre passerelle.
Je préfère niveau maintenabilité qu'un particulier, mais quid des données/stockage/revente effectivement ;)
