### ISSUE TITLE
Mise a jour compatibilité 

### ISSUE THREAD

**Issue by JeremC82** [Sigri44/sigri_linky#22]
Bonjour as t on une idee de la date pour un plugin de nouveau fonctionnel , suite au mise a jour d enedis ? Merci

**Comment by Sigri44** [comment]
> 
> 
> Bonjour as t on une idee de la date pour un plugin de nouveau fonctionnel , suite au mise a jour d enedis ? Merci

Bonjour aucune mise à jour n'est prévu, il faut partir sur un nouveau module complet qui utilise Datahub de Enedis.
