### ISSUE TITLE
ENEDIS

### ISSUE THREAD

**Issue by Frenchkiss5284** [Sigri44/sigri_linky#23]
Bonjour Sigri44,

Concernant le capchat d'Enedis,
ne serait il pas possible de récupérer les données sur le site EDF ?
https://equilibre.edf.fr/
Sachant que sur le contrat Enedis nous donnons notre accord à une tierce partie pour qu'elle ai accès aux données.

ceci serait valable uniquement pour ceux qui sont restés effectivement chez eux.
ou alors il faut faire une version pour chaque fournisseur ...

bien à toi.
Francis

**Comment by Sigri44** [comment]
Hello,

EDF != Enedis. C'est Enedis qui gère le Linky, pas EDF. Ça ne concerne donc aucun des 200 autres fournisseurs d'énergie malheureusement.
De plus désormais le plugin est géré officiellement dans Jeedom :)
