### ISSUE TITLE
Class 'object' not found

### ISSUE THREAD

**Issue by nicozi78** [Sigri44/sigri_linky#7]
Bonjour
Je viens d'installer le plugin linky en suivant le tuto. tout a bien fonctionné. Lorsque j'essaie de l'activer, j'ai un message "class 'object' not found" qui apparait dans un beau cadre rouge.
J'ai essayé de reinstaller le plugin, mais pareil.
Mon Jeedom tourne sur une Debian 10 Buster. Jeedom en version 4.0.21

Merci d'avance pour votre aide, bonne journée

**Comment by nicozi78** [comment]
J'ai modifié la ligne "foreach (object::all() as $object) " par "foreach (jeeObject::all() as $object) " dans le fichier sigri_linky.php.
Cela m'a permis de pouvoir configurer le plugin avec mon login enedis.
Après un délai d'environ 1h, la récup de données a fonctionné

**Comment by jandry** [comment]
Merge request également proposée par jpty dans issue #9
ça fonctionne pour moi aussi

**Comment by Sigri44** [comment]
Hello, merci pour les remontés, du coup je regroupe !

Duplicate of #9
